export const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  TUTORS: '/tutors',
  TUTOR_PROFILE: (id: string) => `/tutors/${id}`,
  PACKAGE: (id: string) => `/packages/${id}`,
  APPLY_AS_TUTOR: '/apply-as-tutor',
  TERMS: '/terms',
  PRIVACY: '/privacy',
  INTEGRITY: '/integrity',
  LOGIN: '/login',
  SIGNUP: '/signup',
  STUDENT: {
    DASHBOARD: '/student/dashboard',
    BOOKINGS: '/student/bookings',
    PACKAGES: '/student/packages',
    PROFILE: '/student/profile',
  },
  TUTOR: {
    DASHBOARD: '/tutor/dashboard',
    APPLICATION: '/tutor/application',
    SUBJECTS: '/tutor/subjects',
    BOOKINGS: '/tutor/bookings',
    PACKAGES: '/tutor/packages',
    NEW_PACKAGE: '/tutor/packages/new',
    PROFILE: '/tutor/profile',
  },
  ADMIN: {
    DASHBOARD: '/admin/dashboard',
    TUTOR_APPLICATIONS: '/admin/tutor-applications',
    USERS: '/admin/users',
    SUBJECTS: '/admin/subjects',
    BOOKINGS: '/admin/bookings',
    PACKAGES: '/admin/packages',
    REPORTS: '/admin/reports',
  },
} as const
